=== Tellenn/tuxLetterGame/TuxEnd3d/src/data/joueur.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema  version="1.0"
            targetNamespace="http://myGame/profile"
            xmlns="http://myGame/profile"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">
    
            <xs:element name="profile" type="Profile"/>
            <xs:complexType name="Profile">
                <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="avatar" type="xs:string"/>
                    <xs:element name="birthday" type="xs:date"/>
                    <xs:element name="games" type="Games"/>
                </xs:sequence>
            </xs:complexType>    
            <xs:complexType name="Games">
                <xs:sequence>
                    <xs:element name="game" type="Game" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
            </xs:complexType>
            <xs:complexType name="Game">
                <xs:all>
                    <xs:element name="time" type="xs:int" minOccurs="0"/>
                    <xs:element name="word" type="Word"/>
                </xs:all>
                <xs:attribute name="date" type="xs:date"/>
                <xs:attribute name="found" type="Found"/>
            </xs:complexType>
            <xs:complexType name="Word">
                <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="level" type="Level"/>
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
            <xs:simpleType name="Found">
                <xs:restriction base="xs:int">
                    <xs:pattern value="[0-9]{2}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType name="Level">
                <xs:restriction base="xs:int">
                    <xs:pattern value="[1-5]"/>
                </xs:restriction>
            </xs:simpleType>
</xs:schema>

=== Tellenn/tuxLetterGame/TuxEnd3d/src/data/joueur.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><profile xmlns="http://myGame/profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/profile file:/home/p/perrink/S5/LangagesPourLeWeb/Tux/Tux/src/xml/joueur.xsd">
    <name>Luke</name>
    <avatar>1</avatar>
    <birthday>1994-10-26</birthday>
    <games>
        <game date="2016-09-25">
            <time>15</time>
            <word level="4">araignee</word>
        </game>
        <game date="2016-09-25" found="85">
            <time>5</time>
            <word level="3">honneur</word>
        </game>
        <game date="2016-11-22" found="0">
            <time>5</time>
            <word level="2">bonjour</word>
        </game>
        <game date="2016-11-22" found="25">
            <time>3</time>
            <word level="1">mois</word>
        </game>
    <game date="2016-11-22"><time>24</time><word level="5">proselytisme</word></game><game date="2016-11-22"><time>18</time><word level="1">mois</word></game>
    <game date="2016-11-24"><time>8</time><word level="1">mois</word></game></games>
</profile>
